### ISSUE TITLE
Move audio equipment sitting in the loading dock to the new location

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#10]
![2016-04-03 15 49 22](https://cloud.githubusercontent.com/assets/5217007/14235545/61461d94-f9b6-11e5-9bb9-0fd946286cc0.jpg)

**Comment by cherukumilli** [comment]
Does anyone know who owns this audio equipment in the loading dock?
Can we donate this equipment? If so, what is a good place to donate this equipment?

**Comment by Russell-Zhang** [comment]
A couple of members expressed their interest in setting up a Dojo media lab for video/audio content production, we can use these for that purpose.

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Are you going to own moving this equipment to the new dojo if the others don't step up?

I just want to make that the others who want to setup a audio/video lab in the new place will follow up on it and this won't be an empty promise :)

**Comment by Russell-Zhang** [comment]
Sure, I'll be the Media Lab Operator

**Comment by cherukumilli** [comment]
OK. Assigned this item to you.
Please close this item after this equipment is moved to the new location.
You will be responsible to move this by yourself i.e., in your car :)

**Comment by cherukumilli** [comment]
Russell help sell this item
