### ISSUE TITLE
Return Beer Keg in the loading dock...

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#12]
![2016-04-03 15 50 16](https://cloud.githubusercontent.com/assets/5217007/14235561/f1fb05f2-f9b6-11e5-8796-0a9e3ba603b9.jpg)

**Comment by echoudhry** [comment]
Where does this need to go?

**Comment by cherukumilli** [comment]
@echoudhry 
@vipjun needs to return it. Its been sitting in the loading dock for a while. 

Jun - Please chime in.

**Comment by appsmatics** [comment]
@vipjun says this is done
