### ISSUE TITLE
Replace bulb on the ceiling over the kitchen in the warehouse area

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#14]
![2016-04-03 17 42 25](https://cloud.githubusercontent.com/assets/5217007/14236080/1a688642-f9c4-11e5-8230-3aad2c0a9479.jpg)

**Comment by cherukumilli** [comment]
- Need volunteers that are certified to use the scissor lift
- Need the volunteer to talk to Jun and get a bulb

**Comment by appsmatics** [comment]
done with @vipjun
