### ISSUE TITLE
Replace bulb on the ceiling over the dinosaur mural in the warehouse area

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#15]
![2016-04-03 17 42 10](https://cloud.githubusercontent.com/assets/5217007/14236125/06c72b10-f9c5-11e5-8b40-0016b0694396.jpg)

**Comment by cherukumilli** [comment]
- Need volunteers that are certified to use the scissor lift
- Need the volunteer to talk to Jun and get a bulb

**Comment by appsmatics** [comment]
done with @vipjun
