### ISSUE TITLE
Fix or Trash broken chair in kitchen

### ISSUE THREAD

**Issue by mikeflores2000** [hackerdojo/new-home#16]
Trash broken chair in kitchen, seat falls off.

**Comment by cherukumilli** [comment]
@mikeflores2000 - I will take a look at it tomorrow evening

**Comment by cherukumilli** [comment]
@mikeflores2000 
I didn't see any broken chairs in the kitchen but I see a lot of broken chairs in the rest of the dojo. I will dump some of them in the next few days.

**Comment by mikeflores2000** [comment]
Look again. The seat slides off on chair next to black table at window in kitchen. Pick up chair and tip over to test.

**Comment by cherukumilli** [comment]
@mikeflores2000 
I will give it another shot at it later today. thx

**Comment by cherukumilli** [comment]
Russell said he will put a couple of screws to tighten the chair. I will assign this issue to @russell-zhang

**Comment by cherukumilli** [comment]
@Russell-Zhang 
I assigned you this issue

**Comment by Russell-Zhang** [comment]
Fixed.
