### ISSUE TITLE
Donate / Trash Lost in Space Robot standee

### ISSUE THREAD

**Issue by mikeflores2000** [hackerdojo/new-home#17]
Donate / Trash Lost in Space Robot standee.
Voice box INOP.

**Comment by cherukumilli** [comment]
@mikeflores2000 - *are you talking about the one in the picture below?*

![img_0644](https://cloud.githubusercontent.com/assets/5217007/14236679/01132fe4-f9ce-11e5-8b28-e0e2c1a0cb7e.jpg)

**Comment by mikeflores2000** [comment]
Affirmative. 

Cheers, Sent from my iPhone
-Support Engineer & Technical Business Analyst-
Mike 415-860-5283

**Comment by cherukumilli** [comment]
ok. I will trash it later this evening when I get to the dojo
