### ISSUE TITLE
Building Inspections

### ISSUE THREAD

**Issue by mikeflores2000** [hackerdojo/new-home#18]
Add contingency new building passes all inspections and any deficiencies repaired by landlord.

**Comment by cherukumilli** [comment]
@mikeflores2000  Adding @vipjun to this ticket so that he can chime in...

**Comment by cherukumilli** [comment]
@vipjun 
I am assigning you this task.
Please feel free to comment / close this issue after it is resolved.

**Comment by cherukumilli** [comment]
@vipjun 
Can this be closed now that we signed the lease?
