### ISSUE TITLE
Replace bulb on the ceiling in the game room area between the kitchen and the restroom

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#22]
![2016-04-03 17 44 17](https://cloud.githubusercontent.com/assets/5217007/14236581/bd9b5864-f9cc-11e5-950d-64eb53cfc051.jpg)

**Comment by appsmatics** [comment]
Replaced one near hallway. This one has a broken holder.
Luminaire 962a holder

**Comment by cherukumilli** [comment]
Thanks Mani @appsmatics 
Can I close this issue?

**Comment by appsmatics** [comment]
Not yet, this particular one needs a holder change or some way to wedge the bulb in. Still open.

**Comment by appsmatics** [comment]
Ok this is done now can be closed.
