### ISSUE TITLE
Repurpose / Donate two unused IBM LAPTOPS

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#25]
![2016-04-03 17 59 10](https://cloud.githubusercontent.com/assets/5217007/14236632/4e907066-f9cd-11e5-9cc7-27ea1df8452b.jpg)

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Any update on these laptops?
Celine is going to GOODWILL mountain view today. If you think these can be donated then please give it to her asap.

**Comment by Russell-Zhang** [comment]
No worries, I'm gonna try set them up to control our 3D printer over the weekend. Will toss them myself if that doesn't work out.

**Comment by Russell-Zhang** [comment]
I just replaced the whole clutter of our front desk sign-in system (desktop PC, Monitor, keyboard, mouse) with one of these laptops. The front desk has never felt so tranquil and minimalist. You'll love it, DC.

**Comment by ghufransyed** [comment]
awesome. It did seem a little strange paying money for a new raspberry pi,
but giving away working laptops.. :)

**Comment by Russell-Zhang** [comment]
@ghufransyed, haha, (at the risk of dating myself) the laptop is the same IBM Thinkpad we used in PriceWaterhouseCoopers back in 2000, I was quite glad to find some use for such an ancient machine.

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Are we going to use these laptops in the new location also? If so, can you take ownership of setting them up at the new location? PLEASE

**Comment by Russell-Zhang** [comment]
Sure thing, I've already replaced the front desk sign-in system with one of these laptops. Will find use for the other one in our new location too

**Comment by Russell-Zhang** [comment]
Re-purposed the second old laptop as a mobile Word/Excel workstation, I'll personally transfer it to new location.
