### ISSUE TITLE
Buy at a minimum 7 bulbs for the ceiling lights

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#26]
Jun / @vipjun ,

Can you please order 7 BIG bulbs for the ceiling lights?

I think you might also need to order one SMALLER one for the light above the bulletin boards.

Please update this issue after you placed the order and after you received the bulbs so that we can work on replacing the bulbs.

**Comment by vipjun** [comment]
ordered 8 lightbulbs in case one does not work.

**Comment by vipjun** [comment]
I think we have some of the smaller bulbs

**Comment by cherukumilli** [comment]
@vipjun - Did we get the bulbs yet? If not, can you please call them and find out when we will get them?

**Comment by cherukumilli** [comment]
@vipjun - I am closing this issue as the new bulbs have arrived
