### ISSUE TITLE
Dump old / broken sofa

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#27]
![2016-04-05 21 06 20](https://cloud.githubusercontent.com/assets/5217007/14325583/e0151a60-fbde-11e5-9ccd-8c6c5774aad3.jpg)

**Comment by cherukumilli** [comment]
Need help dismantling this sofa so that it will fit into the dumpster.

**Comment by mikeflores2000** [comment]
Wish I was told earlier. I have tools when I dismantled my sofa last year. 

Cheers, Sent from my iPhone
-Support Engineer & Technical Business Analyst-
Mike 415-860-5283

**Comment by cherukumilli** [comment]
@mikeflores2000 
Please let me know if you are planning to come to the dojo in the near future. I would love to take your help in dismantling this sofa.

**Comment by mikeflores2000** [comment]
DC,

Will do.  Be very careful not to injury yourself.  Typically coil springs
and razor sharp edges abound.

Cheers,
Sent from my Macbook Pro
-Experienced Support Engineer and Technical Business Analyst-
http://www.linkedin.com/in/mikeflores2000

Mike 415-860-5283

**Comment by cherukumilli** [comment]
@mikeflores2000 
One more question...Do you think having a Hacker Dojo Garage sale to dispose of the sofa and some of the tables is a good idea?

**Comment by cherukumilli** [comment]
Dumped it with Russell's help
