### ISSUE TITLE
Remove 'hack reactor' door lock on move-out on May 29

### ISSUE THREAD

**Issue by ghufransyed** [hackerdojo/new-home#28]

**Comment by cherukumilli** [comment]
@ghufransyed 
Looks like in that case we need to remove the HIVE room door lock also. I will add another item for that.

**Comment by cherukumilli** [comment]
@ghufransyed @vipjun Do we need another task to buy and put a normal door knob in the hole left after removing the door lock?

**Comment by appsmatics** [comment]
why wait so long the room is empty. we can close this out rightaway (after changing of course)

**Comment by appsmatics** [comment]
Changed back to regular handle with @vipjun
