### ISSUE TITLE
Transport Hack Reactor monitors on May 30

### ISSUE THREAD

**Issue by ghufransyed** [hackerdojo/new-home#29]
Jun, can you confirm how many of these there are that belong to the Dojo, and what size?

**Comment by marieknox** [comment]
4, they are wide screen I believe 27 inches

**Comment by cherukumilli** [comment]
@vipjun 
Looks like you are using @marieknox's github userid for some reason. 

adding @ghufransyed also on this thread

**Comment by appsmatics** [comment]
4, they are wide screen I believe 27 inches they are in the storage room at present

**Comment by cherukumilli** [comment]
Jun and team completed this task
