### ISSUE TITLE
Remove Red Cubicle Dividers

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#3]
Remove 3 RED cubicle dividers

![img_0623](https://cloud.githubusercontent.com/assets/5217007/14235363/f75452d4-f9b0-11e5-85bd-d2f4f1744ec3.jpg)

**Comment by cherukumilli** [comment]
The cubicle dividers have to be removed and the holes have to be plugged

**Comment by Qyoom** [comment]
What then needs to happen to the dividers? Also, do we have plaster for the holes?

**Comment by cherukumilli** [comment]
@Qyoom  - The plan is to use these cubicle dividers in the new facility. If I remember correctly, Jun was saying Frank Rothacker will be able to help remove the dividers and plug the holes.

I was wondering if we can start taking them out right now instead of waiting till the last minute. I am pretty sure we will discover a ton of other tasks that we have to do towards the end. What do you think?

**Comment by cherukumilli** [comment]
Richard took out ONE of the cubicle dividers. Helped him in moving it to the wall next to electrical room and fire exit.

**Comment by cherukumilli** [comment]
![2016-04-05 21 12 33](https://cloud.githubusercontent.com/assets/5217007/14325615/fc56aba8-fbde-11e5-88b7-b930ba6b6445.jpg)

**Comment by Qyoom** [comment]
Frank took out 3 dividers today and plugged the floor holes. He gets the bulk of the credit and my vote for member of the month!

**Comment by cherukumilli** [comment]
@Qyoom @frankhd 
Can we close this task? or do you think there is more left?

**Comment by frankhd** [comment]
One more divider is left, plus plugging up the holes in the floor and walls.

**Comment by cherukumilli** [comment]
@frankhd 
Can we consider this task as completed? If so, can we close this task?

**Comment by cherukumilli** [comment]
plugged the holes with putty
