### ISSUE TITLE
Remove 'HIVE' door lock on move-out and replace with regular door knob on May 30

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#30]
@vipjun @ghufransyed 
Do we need another task to buy and put a normal door knob in the hole left after removing the door lock?

**Comment by ghufransyed** [comment]
Yes, I assume we still have the old one @vipjun ?

**Comment by marieknox** [comment]
does replying work ? yes I believe we have the old door hardware in the
janitors closet

**Comment by ghufransyed** [comment]
Jun, looks like you are still listed as 'Marie' : if it's your account, you
should probably just change your name in the profile

**Comment by marieknox** [comment]
test

**Comment by vipjun** [comment]
test again

**Comment by frankhd** [comment]
We had a box of locks and parts in the electrical utility room, however many things seem to be missing, including a wrench I made for installing the locks.

**Comment by cherukumilli** [comment]
Jun and team completed this task
