### ISSUE TITLE
Setup network at new location

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#31]
Need to move all the equipment from the current location to the new home and setup the network in the new location.

**5000 sqft space**
- [x] Setup service with ISP (AT&T? Comcast?)
- [x] Run cables
- [x] Setup routers

**9000 sqft space**
- [ ] Setup service with ISP (AT&T? Comcast?)
- [ ] Run cables
- [ ] Setup routers

**Comment by cherukumilli** [comment]
@ sunnguyen1
We will be using this item to track the setup of the network in the new location.

@vipjun 
Sun also volunteered to help with the network setup in the new location. He has been an excellent volunteer of late and has been helping man the front desk lately. 
How can Sun help? Can you please talk to him today at the dojo?

**Comment by cherukumilli** [comment]
@sunnguyen1 
Did you get a chance to check out the new location?
If so, did you figure out a day you would like to install the network in the new location?
Please keep update this task with the status

**Comment by vipjun** [comment]
I was with sun yesterday at the new loc. Larry was there as well .  Internet should be up soon in the temp space

**Comment by sunnguyen1** [comment]
I will spend this Saturday 5/28/2016 to have the network ready at our new location.

**Comment by cherukumilli** [comment]
@sunnguyen1 
Awesome!!!

**Comment by vipjun** [comment]
@sunnguyen1 

Hi Sunny, Please coordinate with Larry on this as well. He was at the facilities today.  I will CC you both on an email

**Comment by sunnguyen1** [comment]
I will work with Larry on this ticket.

**Comment by sunnguyen1** [comment]
Worked with Larry on this ticket. We got the network up and working at the new Dojo temp side of the building.

**Comment by cherukumilli** [comment]
network is up and running
