### ISSUE TITLE
Move HP Sprout machines to new location

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#32]
There are two HP sprout machines that no one uses between the vending machines and the makerspace. These machines are NOT owned by Hacker Dojo so they need to be returned back to HP.

![4329901_sd](https://cloud.githubusercontent.com/assets/5217007/14406651/7cd4e800-fe62-11e5-83ea-70d056624fb7.jpg)

**Comment by cherukumilli** [comment]
@vipjun 
Can you please post the HP contact email address? One of us can contact them to pick up these machines.

**Comment by ghufransyed** [comment]
These machines actually look pretty awesome, it's hard to believe we
couldn't find a use for them? Could we keep them for now, if I can't find a
use for them, I'll arrange to give them back to HP or donate them elsewhere
and submit the receipt.

**Comment by cherukumilli** [comment]
@ghufransyed 
We don't own these machines. HP still owns them. We can't donate them as far as I know.

IMHO... If no one used these machines for the past two years then I doubt anyone will use these machines in the near future. Also, one of the machines stays unplugged all the time. I think it is taking up unnecessary space and power (like a vampire).

I am assigning this task to you. :)

**Comment by Russell-Zhang** [comment]
No worries, Michael Chung and I just talked and we'll set them up for our Arduino Robotics classes later. The touch screen is convenient for ArduBlock drag-n-drop programming for the kids we're teaching.

**Comment by cherukumilli** [comment]
@Russell-Zhang 
I re-opened this task.
Are you planning to install new software on it?
If so, we need to find out if HP will be OK with it.

**Comment by Russell-Zhang** [comment]
Alrighty, I'll check with HP on Monday and post our findings.

**Comment by Russell-Zhang** [comment]
Just talked to both a sales specialist and a customer rep from HP. Neither have a clue about exactly how HP would handle these demo units. They don't see any problems with installing third-party software on the machines, besides we can easily remove any installed programs.

I'll proceed with the original plan and transport the machines to 3350 Thomas Rd personally so they don't become logistic burdens for Dojo.

**Comment by vipjun** [comment]
Can we hack them into signin kiosks ?

**Comment by Russell-Zhang** [comment]
@vipjun, that would require rewriting our sign-in apps from a scratch as far as I know. Dojo infrastructure is based in Linux, OS X or iOS environments. These machines on the other hand are highly customized Windows PCs. We should be able to replace some of the bulky front desk Linux machines with Raspberry Pi though.

**Comment by vipjun** [comment]
HP reps have not been coming to the location to service the computers.  We have no agreement with them.  It is fair game for how we decide to use them.

**Comment by Russell-Zhang** [comment]
One is broken, I'm developing a virtual robotics lab on the other. Will transport to the new location myself.

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Can we close this task?

**Comment by Russell-Zhang** [comment]
Sure, thanks.
