### ISSUE TITLE
Trash or donate Brother HL-2270DW printer 

### ISSUE THREAD

**Issue by mikeflores2000** [hackerdojo/new-home#35]
Needs a new laser cartridge.  I may have one but cannot find it.
Printer was donated last year to the Dojo.

**Comment by cherukumilli** [comment]
@mikeflores2000 
I wonder if we can donate a few of the other printers too.
Most of them are not used because they are either out of paper or ink cartridge.

**Comment by mikeflores2000** [comment]
Keep only big Brother and color HP. 

Cheers, Sent from my iPhone
-Support Engineer & Technical Business Analyst-
Mike 415-860-5283

**Comment by cherukumilli** [comment]
Part of the moving sale. If it is not sold then will donate it to Goodwill.
