### ISSUE TITLE
Move The Digital Piano in Large Event Room to the new location

### ISSUE THREAD

**Issue by Russell-Zhang** [hackerdojo/new-home#36]
It was donated by a Chinese startup that makes these pianos. We can sell them in a garage sale and apply the proceeds towards our future media lab.

**Comment by cherukumilli** [comment]
+1

**Comment by mikeflores2000** [comment]
Hi DC,

Could you unsubscribe me from new-home github?

Cheers, Sent from my iPhone
-Support Engineer & Technical Business Analyst-
Mike 415-860-5283

**Comment by ghufransyed** [comment]
@mikeflores2000 : just click the link to open the page on github, then click 'unsubscribe' on the right hand side of the screen. I'm guessing you don't use git much at work?  :)

**Comment by appsmatics** [comment]
john sokol put a bid on it during a member meeting. Not sure if he wants it. we could use it in the new place lobby area. Who knows might have a piano wo/man joining.

**Comment by cherukumilli** [comment]
@appsmatics 
My only fear is that it will shunted into a corner even in the new place. If a big warehouse like 599 can't find a place for it then I don't know how we will be able to accommodate it in the new place.

Currently, @Russell-Zhang  is the only one that uses this piano (may be once a week).

Also, does the cost of moving it justify keeping it?

@vipjun - Please chime in here...Do you think we will have room to put this piano in the new place?

**Comment by appsmatics** [comment]
Having something funky like a piano is a good thing. Its free and in good condition. Maybe we can get some students from music schools to come and play. Maybe someone will make a robot to play a piano !
It hardly takes up space. It should have been put in the front not in the LER.

**Comment by cherukumilli** [comment]
@appsmatics 
Sounds good. Let me close this task then. 
We will plan on moving it to the new location.

**Comment by cherukumilli** [comment]
Actually, let me change the description to reflect that we will be moving the piano to the new location

**Comment by vipjun** [comment]
Landlord said Piano in the lobby would be okay, but we won't be able to put
other things there.

**Comment by cherukumilli** [comment]
Russell and team completed this task
