### ISSUE TITLE
Disconnect the Projectors in the Large Event Room and Conference room and package it for shipment

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#37]
Need a volunteer to use the scissor lift to and remove the projector in the large event room and use a ladder to unhook the projector in the classroom

**Comment by frankhd** [comment]
You mean ceiling, not roof.  No one should go on the roof.

**Comment by cherukumilli** [comment]
@frankhd 
Pardon my limited english vocabulary. Yes, it is ceiling I am talking about.

**Comment by cherukumilli** [comment]
Jun and team completed this task
