### ISSUE TITLE
Help clean up the library by donating or recycling old technical books that are no longer used

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#43]
Need a volunteer to:
1. Identify old technical books like Visual Basic 6, Win 32 API fundamentals and other books that are no longer used and relevant
2. Pack them into boxes
3. Donate them to the nearest library OR drop it off at a book recycling center

**Comment by mikeflores2000** [comment]
Please recycle obsolete books. Don't want to pollute young minds with obsolete tech skills. 
It's bad enough holding current skills gets you the unemployment line. 

My nephew makes $100 an hour and he can't 
decipher a 1 from a 0 in the context of computers. 

No wonder America has to import 
H1B along with oil and drugs. 
Shame on us.  Ron Paul is vindicated. 

Cheers, Sent from my iPhone
-Goof ball -
Mike 415-860-5283

**Comment by cherukumilli** [comment]
Cleaned up most of the old and useless books with Russell's help today
