### ISSUE TITLE
Sell Outdoor Patio Heaters

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#45]
There are 3 portable patio propane heaters.

We won't need them in the new location. Need to sell them.

Any volunteers?

**Comment by cherukumilli** [comment]
![20160419_105813](https://cloud.githubusercontent.com/assets/5217007/14714356/4c7d2d74-07aa-11e6-9e42-9c69a31e4706.jpg)
![20160419_105846](https://cloud.githubusercontent.com/assets/5217007/14714367/5c56d434-07aa-11e6-8940-c038afeac463.jpg)

**Comment by Russell-Zhang** [comment]
Ralph mentioned that Thomas paid for them but was not reimbursed by Dojo, Mike Chung was supposed to contact Thomas to find out it he wants them back before we sell them. I'll remind Chung and Tom on Friday night.

**Comment by ghufransyed** [comment]
If it was an approved purchase, shouldn't we offered to reimburse him (
assuming he has the receipts) ?

If Thomas wants to consider them a donation to the dojo (for us to sell),
we should at least offer to give him a receipt, it would save him some
money on taxes

**Comment by cherukumilli** [comment]
@Russell-Zhang @ghufransyed 
I thought I saw an email or slack from Ralph saying that even though Tom didn't get reimbursed, he doesn't want it back. He wants to consider it more like a donation to the dojo now. May be Michael Chung can confirm.

**Comment by cherukumilli** [comment]
Sold one to Ali for $xxx (by Jun)

**Comment by cherukumilli** [comment]
Sold two more to the chinese lady who comes to the weekend morning tutoring sessions
