### ISSUE TITLE
Update wikipedia article about Hacker Dojo

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#47]
Wikipedia article at https://en.wikipedia.org/wiki/Hacker_Dojo needs to be updated after the move to 3350 Thomas Rd.

**Comment by dustball** [comment]
You aren't supposed to edit wikipedia articles about yourself.  What the hell, bro.

**Comment by frankhd** [comment]
I added the new address.  I will also add a photo of the outside of
the building.

**Comment by cherukumilli** [comment]
@dustball 
The intent of this task was to submit a request edit for the new location. I was not planning on editing it myself. :)

**Comment by dustball** [comment]
I'm not an idiot.  It's still wrong.  You and frank have a conflict of interest.  

But that's Okay, rules don't apply to you, right?  Hope you all end up in jail for trying to hide embezzlement.

https://en.wikipedia.org/wiki/Wikipedia:FAQ/Organizations

**Comment by ghufransyed** [comment]
Brian, you are the founder of a competing hackerspace,
https://atribecalled650.pbworks.com . You're making public allegations of
illegal behavior by Diwakar. You have not gone to the police about this,
because there is no evidence to support your allegations.
Is that a conflict of interest? Or do those rules only apply where Person
!= "Brian Klug" ?

**Comment by mikeflores2000** [comment]
I read the wiki link about conflict of interest. 
Brian is right and his point is Hacker Dojo needs
to play by the same rules everyone else does. 
He and and any reasonable person who respects the rule of law would understand this. 

Blowing smoke and obfuscation has no place and
no one at the Hacker Dojo is above the rule of law. 
Wouldn't you agree? 

We applaud your donation of $10000 however. 
Let's hope it is put to better use with proper financial
oversight. 
Cheers, Sent from my iPhone
Mike

**Comment by ghufransyed** [comment]
Mike, you appear to be defining  'obfuscation' as "facts I don't want to
respond to"

Regarding the central point, what is the 'conflict' in correcting an
address when we move? The dojo and any readers of wikipedia are both served
by having an accurate address listed. And Frank has no formal connection to
the running of the dojo, he's just a very much appreciated volunteer.

Seeing as you were celebrating the end of your hacker dojo membership this
week, and implying it was not good value for you, remind me again why you
are spending time on the dojo's github issues?  The dojo has lots of
software maintenance and upgrades you could help with, but I guess that
would be real work, right?

Alternatively, I'm sure Brian klug would love to have you help build his
new hackerspace with him, wouldn't that be more useful than dealing with us
idiots at the hacker dojo? And yet here you are. I guess trolling is more
satisfying to some people than actually building something.

**Comment by ghufransyed** [comment]
So to actually focus on the mechanism, looks like we would add a [request edit](https://en.wikipedia.org/wiki/Template:Request_edit) to the [talk page](https://en.wikipedia.org/wiki/Talk:Hacker_Dojo)

**Comment by cherukumilli** [comment]
@ghufransyed 
That is what I was suggesting in my response to dustball.
