### ISSUE TITLE
Light just as you enter mens not working

### ISSUE THREAD

**Issue by appsmatics** [hackerdojo/new-home#48]
Tried changing bulbs still glowing orange. Needs new ballast.

**Comment by frankhd** [comment]
I have a ballist on order.

**Comment by appsmatics** [comment]
Frank we need one more ballast. Same type of lamp along the walkway. You will see it as i left it out of the ceiling.

**Comment by frankhd** [comment]
I have two ballasts on order, because I was not completely certain
about which would work.  Perhaps, both will work, in which case I can
replace the one in the walkway.

**Comment by cherukumilli** [comment]
Frank fixed this on friday
