### ISSUE TITLE
3 ceiling lamps in corridor between conference rooms

### ISSUE THREAD

**Issue by appsmatics** [hackerdojo/new-home#49]
#@vipjun  has ordered the lamps

**Comment by appsmatics** [comment]
changed bulbs in 2 of them OK now. One needs a new ballast.

**Comment by cherukumilli** [comment]
@appsmatics 
Frank fixed the ballast in the restroom. He said he won't be able to make it this week as he will be out of town. Will you be able to fix the ones between the conference rooms. @Russell-Zhang or @vipjun or Jonathan or Stewart will be able to help you.

**Comment by appsmatics** [comment]
its a bit of a pain as the ballast is in the false ceiling with short leads ... but we will look at it

**Comment by cherukumilli** [comment]
@appsmatics 
Should we call an electrician to help fix this? @vipjun, @sunnguyen1 and @Russell-Zhang are also there to help. I will be there in the evening around 7:30 pm to help also (if there is anything else that is remaining).

**Comment by appsmatics** [comment]
never ! will know today, when I try it.

**Comment by appsmatics** [comment]
Ok this is done now. All lamps in the Dojo are lit.
We have 100 % lamp coverage !
