### ISSUE TITLE
Replace missing/bad ceiling tiles in the conference room, classroom, loungey and other areas

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#51]
Volunteers Needed!!!

- Please help identify how many ceiling tiles are 

1. Missing
2. Broken / bad
 
- Work with Jun or go to Home Depot or the nearest hardware store to buy ceiling tiles of CORRECT DIMENSION, TEXTURE, COLOR, etc
 
- Replace the tiles on the ceiling

- Please talk to Jun Wong if you have more questions.

**Comment by appsmatics** [comment]
Maker space:
@Russell-Zhang tubes in 2 fixtures to working ballast and changed a few more
All classrooms and conference room lights are working now.
