### ISSUE TITLE
Move and Setup Mag-Lock and Sign-In Machines

### ISSUE THREAD

**Issue by Russell-Zhang** [hackerdojo/new-home#52]
John Sokol and I have been working on this already

**Comment by vipjun** [comment]
The landlord is looking to purchase an off the shelf / installed solution . Can You and John look into one that can communicate via api ? Land lord is willing to pay ~$500 month for the building as a support contract.

**Comment by Russell-Zhang** [comment]
yeah, we've started looking into vendors few weeks ago, will forward the finding to you

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Are we still looking into this?
Can @sunnguyen1 help research, recommend and setup a system for us?

**Comment by Russell-Zhang** [comment]
Yup, it's on-going, we'll co-ordinate with the landlord to make sure our system works with the new ones he's putting in.

**Comment by cherukumilli** [comment]
@Russell-Zhang 
Can I close this issue?

**Comment by Russell-Zhang** [comment]
Sure, the sign-in machines have been working since early June and we've
retired our old mag-lock system.

-- from my phone, pls excuse brevity & typos
