### ISSUE TITLE
Send an invoice to squiffyclean for buying the industrial kitchen oven...

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#59]
Simon bought the industrial kitchen oven for $50.
Simon would like an invoice to SquiffyClean so that he can expense it.

Please send an invoice to Simon:  simon@squiffyclean.com.

**Comment by cherukumilli** [comment]
@vipjun 
is this taken care of?
If so, can you please add your comments and close this?

**Comment by cherukumilli** [comment]
is this taken care of? If so, can you please close this item?

**Comment by vipjun** [comment]
Invoice sent
