### ISSUE TITLE
Trash the second Foosball table also

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#6]
![2016-04-03 15 46 38](https://cloud.githubusercontent.com/assets/5217007/14235485/8662a8f6-f9b4-11e5-8675-6128a166a878.jpg)

**Comment by cherukumilli** [comment]
This second foosball table is also broken. We would like to dump this foosball table also. Any comments?

It is in the loading dock btw.

**Comment by dineshone** [comment]
If it is not too damaged, I can try and fix it and we can reuse it.

**Comment by vipjun** [comment]
The second one should be thrown out.

**Comment by cherukumilli** [comment]
@dineshone - I think both the foosball tables can be fixed. I don't think we have room to keep them in the new place. The question is even if someone fixes it, should we still donate it as we won't have room for it in the new place.

**Comment by cherukumilli** [comment]
@dineshone - I assigned you this task. Please let me know if you are not interested in taking this task.

**Comment by cherukumilli** [comment]
Jun dumped it in the trash bin for the city to pick up
