### ISSUE TITLE
Donate unused old monitors in the loading dock

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#7]
![2016-04-03 15 47 29](https://cloud.githubusercontent.com/assets/5217007/14235505/18f8e0f4-f9b5-11e5-8651-26f471bf5ce6.jpg)

**Comment by cherukumilli** [comment]
Anyone have any suggestions on the best way to dispose off these old unused monitors in the loading dock?

**Comment by cherukumilli** [comment]
Many thanks to Celine for volunteering to drop off 3 of these old monitors at the Goodwill - mountain view donation center

**Comment by echoudhry** [comment]
We can take these to weird warehouse not to far

**Comment by cherukumilli** [comment]
@echoudhry 
Celine volunteered to drop off the rest of the old monitors at Goodwill - mountain view

**Comment by cherukumilli** [comment]
Goodwill - Mountain View Donation Receipt

![2016-04-08 14 31 09](https://cloud.githubusercontent.com/assets/5217007/14406207/18ad838e-fe56-11e5-8e65-4d6ecbb785d7.jpg)
