### ISSUE TITLE
Sell UNUSED space heater

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/new-home#8]
![2016-04-03 15 47 43](https://cloud.githubusercontent.com/assets/5217007/14235510/44900e90-f9b5-11e5-9343-fbceedbafb28.jpg)

**Comment by cherukumilli** [comment]
This unused space heater IMO is a fire hazard. Does anyone know what to do with this one? Anyone know if this can be donated? or how to dispose it off?

**Comment by cherukumilli** [comment]
This space heater is currently in the loading dock

**Comment by eadsjr** [comment]
I can dispose of this for you

**Comment by cherukumilli** [comment]
@eadsjr 
I have been requested to host a Garage sale or talk to local furniture resale companies to see if they want to buy our excess furniture and some of the goods like this space heater. 

After the garage sale, if no one buys it then I will come back to you and beg you to dispose it. :)

**Comment by cherukumilli** [comment]
Mani volunteered to donate this item to Goodwill
